
CREATE OR REPLACE FORCE VIEW WBSC.COURSE_TEACHER_COMPARE
(COURSE_FACULTY, COURSE_SHORTNAME, COURSE_FULLNAME, STAFF_ID, FULLNAME_THA,
 USER_ID, CITIZEN_CODE, USERNAME, IDNUMBER, FIRSTNAME,
 LASTNAME, USERROLE, ACTION)
AS
SELECT

    COALESCE(CT_GP.FA_NAME_TH, CTD.CAT_TERM) AS COURSE_FACULTY,
    COALESCE(CT_GP.COURSE_SHORTNAME, CTD.COURSE_SHORTNAME) AS COURSE_SHORTNAME,
    COALESCE(CT_GP.COURSE_FULLNAME, CTD.COURSE_FULLNAME) AS COURSE_FULLNAME,
    CT_GP.STAFF_ID,
    CT_GP.FULLNAME_THA,
    CT_GP.USER_ID,
    CT_GP.CITIZEN_CODE,
    CTD.USERNAME,
    CTD.IDNUMBER,
    CTD.FIRSTNAME,
    CTD.LASTNAME,
    CTD.USERROLE,
    CASE
        WHEN CTD.COURSE_SHORTNAME IS NULL THEN 'Add'
        WHEN CT_GP.COURSE_SHORTNAME IS NULL THEN 'Del'
        ELSE 'Match'
    END AS ACTION
FROM
    (
        SELECT DISTINCT
            CT.FA_NAME_TH,
            CT.COURSE_SHORTNAME,
            CT.COURSE_FULLNAME,
            CT.STAFF_ID,
            GP.FULLNAME_THA,
            GP.USER_ID,
            GP.CITIZEN_CODE
        FROM SDUEDU.VW_WBSC_COURSE_TEACHER682 CT
            LEFT JOIN VW_HR_PROFILE@LNK_RSDUE2M_SDPERSON GP
                ON CT.STAFF_ID = GP.CODE_PERSON
    ) CT_GP
    FULL OUTER JOIN
    (
        SELECT DISTINCT
            CAT_TERM,
            COURSE_SHORTNAME,
            COURSE_FULLNAME,
            USERNAME,
            IDNUMBER,
            FIRSTNAME,
            LASTNAME,
            USERROLE
        FROM WBSC.COURSE_TEACHER_DETAILED
    ) CTD
        ON CT_GP.COURSE_SHORTNAME = CTD.COURSE_SHORTNAME
        AND CT_GP.CITIZEN_CODE = CTD.IDNUMBER
ORDER BY
    COALESCE(CT_GP.FA_NAME_TH, CTD.CAT_TERM),
    COALESCE(CT_GP.COURSE_SHORTNAME, CTD.COURSE_SHORTNAME),
    ACTION DESC;
