CREATE OR REPLACE FORCE VIEW WBSC.VW_WBSC_ENROLL682
(STD_ID, ID_CARD_CODE, STD_CODE, STD_ENROLL_KEY, USERNAME,
 PREFIX_NAME_TH, FIRST_NAME_TH, LAST_NAME_TH, PREFIX_NAME_EN, FIRST_NAME_EN,
 LAST_NAME_EN, DEFORM_NAME_TH, EDULEVELCODE, EDULEVELNAMETH, STUDENTGROUPCODE,
 STUDENTGROUPNAMETH, STUDYTYPECODE, STUDYTYPENAMETH, STUDYTIMECODE, STUDYTIMENAMETH,
 SITECODE, SITENAMETH, FACULTYCODE, FACULTYNAMETH, MAJORCODE,
 MAJORNAMETH, CURRICULUMCODE, CURRICULUMNAMETH, ACADEMIC_YEAR, SEMESTER,
 SECTION_ID, SECTION_CODE, SUB_CODE, SUB_SHOW, SUB_NAME_TH,
 SUB_NAME_EN, CREDIT, REG_TRNS_COURSE_ID, CREATED_DT, REG_COURSE_STATUS_ID,
 STATUS_NAME_TH, IS_APPROVE, IS_APPROVE_DESC, UPDATED_DT, UPDATED_BY,
 CLASS_DATES, SUB_COUNT, STATE_DIRECTION)
AS
SELECT EN."STD_ID",EN."ID_CARD_CODE",EN."STD_CODE",EN."STD_ENROLL_KEY",EN."USERNAME",EN."PREFIX_NAME_TH",EN."FIRST_NAME_TH",EN."LAST_NAME_TH",EN."PREFIX_NAME_EN",EN."FIRST_NAME_EN",EN."LAST_NAME_EN",EN."DEFORM_NAME_TH",EN."EDULEVELCODE",EN."EDULEVELNAMETH",EN."STUDENTGROUPCODE",EN."STUDENTGROUPNAMETH",EN."STUDYTYPECODE",EN."STUDYTYPENAMETH",EN."STUDYTIMECODE",EN."STUDYTIMENAMETH",EN."SITECODE",EN."SITENAMETH",EN."FACULTYCODE",EN."FACULTYNAMETH",EN."MAJORCODE",EN."MAJORNAMETH",EN."CURRICULUMCODE",EN."CURRICULUMNAMETH",EN."ACADEMIC_YEAR",EN."SEMESTER",EN."SECTION_ID",EN."SECTION_CODE",EN."SUB_CODE",EN."SUB_SHOW",EN."SUB_NAME_TH",EN."SUB_NAME_EN",EN."CREDIT",EN."REG_TRNS_COURSE_ID",EN."CREATED_DT",EN."REG_COURSE_STATUS_ID",EN."STATUS_NAME_TH",EN."IS_APPROVE",EN."IS_APPROVE_DESC",EN."UPDATED_DT",EN."UPDATED_BY",EN."CLASS_DATES", ET.SUB_COUNT, ET.STATE_DIRECTION
FROM SDUEDU.VW_WBSC_COURSE_ENROLE682 EN
    INNER JOIN SDUEDU.VW_WBSC_COURSE_ENROLL_TARGET ET ON EN.STD_CODE = ET.STD_CODE AND EN.ACADEMIC_YEAR = ET.ACADEMIC_YEAR AND EN.SEMESTER = ET.SEMESTER AND EN.REG_TRNS_COURSE_ID = ET.TARGET_TRNS_COURSE_ID
WHERE 1=1
       AND ( EN.ACADEMIC_YEAR = '2568' AND EN.SEMESTER = '2' )
       -- AND ET.STATE_DIRECTION = 'KEEP COURSE'
       -- AND TO_NUMBER(TO_CHAR(EN.CREATED_DT,'YYYYMMDD')) >= '20221213'
      -- AND EN.IS_APPROVE = '2'
;
