CREATE OR REPLACE FORCE VIEW SDUEDU.VW_WBSC_COURSE_ENROLE682
(STD_ID, ID_CARD_CODE, STD_CODE, STD_ENROLL_KEY, USERNAME,
 PREFIX_NAME_TH, FIRST_NAME_TH, LAST_NAME_TH, PREFIX_NAME_EN, FIRST_NAME_EN,
 LAST_NAME_EN, DEFORM_NAME_TH, EDULEVELCODE, EDULEVELNAMETH, STUDENTGROUPCODE,
 STUDENTGROUPNAMETH, STUDYTYPECODE, STUDYTYPENAMETH, STUDYTIMECODE, STUDYTIMENAMETH,
 SITECODE, SITENAMETH, FACULTYCODE, FACULTYNAMETH, MAJORCODE,
 MAJORNAMETH, CURRICULUMCODE, CURRICULUMNAMETH, ACADEMIC_YEAR, SEMESTER,
 SECTION_ID, SECTION_CODE, SUB_CODE, SUB_SHOW, SUB_NAME_TH,
 SUB_NAME_EN, CREDIT, REG_TRNS_COURSE_ID, CREATED_DT, REG_COURSE_STATUS_ID,
 STATUS_NAME_TH, IS_APPROVE, IS_APPROVE_DESC, UPDATED_DT, UPDATED_BY,
 CLASS_DATES)
AS
SELECT  R.STD_ID, S.ID_CARD_CODE , S.STD_CODE
    , S.STD_CODE||'-'||R.ACADEMIC_YEAR||'-'||R.SEMESTER||'-'||SUB.SUB_SHOW AS STD_ENROLL_KEY
    ,CASE
        WHEN (CUR.EDULEVELCODE = '2' OR CUR.EDULEVELCODE = '4') THEN 'u'||S.STD_CODE
        WHEN CUR.EDULEVELCODE = '5' THEN 'g'||S.STD_CODE
        ELSE NULL
     END AS USERNAME
   ,PFIX.PREFIX_NAME_TH, S.FIRST_NAME_TH, S.LAST_NAME_TH,
   PFIX.PREFIX_NAME_EN, S.FIRST_NAME_EN, S.LAST_NAME_EN, DFF.DEFORM_NAME_TH
   ,CUR.EDULEVELCODE , CUR.EDULEVELNAMETH
   , CUR.STUDENTGROUPCODE, CUR.STUDENTGROUPNAMETH, CUR.STUDYTYPECODE, CUR.STUDYTYPENAMETH, CUR.STUDYTIMECODE, CUR.STUDYTIMENAMETH,
   CUR.SITECODE, CUR.SITENAMETH, CUR.FACULTYCODE, CUR.FACULTYNAMETH, CUR.MAJORCODE, CUR.MAJORNAMETH, CUR.CURRICULUMCOE AS CURRICULUMCODE, CUR.CURRICULUMNAMETH,
    R.ACADEMIC_YEAR, R.SEMESTER, C.SECTION_ID, SEC.SECTION_CODE,
    SUB.SUB_CODE, SUB.SUB_SHOW , SUB.SUB_NAME_TH, SUB.SUB_NAME_EN, SUB.CREDIT, C.REG_TRNS_COURSE_ID, C.CREATED_DT, C.REG_COURSE_STATUS_ID, TCS.STATUS_NAME_TH
    ,C.IS_APPROVE
    , CASE
        WHEN C.IS_APPROVE = '1' THEN 'อนุมัติ'
        WHEN C.IS_APPROVE = '2' THEN 'รออนุมัติ'
    END AS IS_APPROVE_DESC
    , C.UPDATED_DT,C.UPDATED_BY, SS.CLASS_DATES
FROM SDUEDU.ENR_T_REG_TRNS_COURSE C
        INNER JOIN SDUEDU.ENR_T_REG_TRNS RT ON C.REG_TRNS_ID = RT.REG_TRNS_ID
        INNER JOIN SDUEDU.ENR_T_REG R ON RT.REG_ID = R.REG_ID
        INNER JOIN SDUEDU.ENR_M_STD S ON R.STD_ID = S.STD_ID
        INNER JOIN SDUEDU.CLS_T_SECTION SEC ON C.SECTION_ID = SEC.SECTION_ID
        INNER JOIN EDUMIS.CURRICULUMS CUR ON S.COPEN_ID = CUR.COPENID
        INNER JOIN EDUMIS.ZPREFIX PFIX ON S.PREFIX_CODE = PFIX.PREFIX_CODE
        INNER JOIN EDUMIS.ZSUBJECT SUB ON SEC.COURSE_CODE = SUB.SUB_CODE
        INNER JOIN EDUMIS.REF_DEFORM DFF ON S.DEFORM_CODE = DFF.DEFORM_ID
        LEFT JOIN SDUEDU.USR_M_STATUS TCS ON C.REG_COURSE_STATUS_ID = TCS.STATUS_ID
        LEFT JOIN (
                SELECT CS.SECTION_ID
                    ,LISTAGG(CS.CLASS_DATE_START, ', ') WITHIN GROUP (ORDER BY CS.CLASS_DATE_START) AS CLASS_DATES
                FROM (
                       SELECT DISTINCT CS2.SECTION_ID, CS2.CLASS_DATE_START
                       FROM SDUEDU.VW_WBSC_COURSE_SCHEDULE CS2
                     ) CS
                GROUP BY CS.SECTION_ID
               ) SS ON SS.SECTION_ID = SEC.SECTION_ID
WHERE R.RECORD_STATUS = 'A'
    AND RT.RECORD_STATUS = 'A'
    AND C.RECORD_STATUS = 'A'
    AND SEC.RECORD_STATUS = 'A'
    AND C.IS_APPROVE IN(1,2)
    AND R.ACADEMIC_YEAR = '2568'
    AND R.SEMESTER = '2'
    AND REG_COURSE_STATUS_ID IN ('22201','22202', '22203','22204')
ORDER BY S.STD_CODE,SUB.SUB_CODE, R.CREATED_DT;
